QUALITY_DIMENSIONS = (
    "scope_boundary",
    "stage_ownership",
    "evidence_discipline",
    "existing_path_fit",
    "reuse_surface_fit",
    "abstraction_fit",
    "flow_readability",
    "data_flow_visibility",
    "business_orchestration",
    "data_flow_integrity",
    "state_transition_integrity",
    "domain_invariant_fit",
    "side_effect_visibility",
    "persistence_access_shape",
    "performance_flow",
    "project_style_fit",
    "response_contract_fit",
    "identifier_authority_location",
    "artifact_quality",
    "adopt_artifact_quality",
    "constitution_fit",
    "constitution_downstream_adherence",
    "multi_stack_fit",
    "verification_evidence",
    "verification_fit",
    "release_claim_discipline",
    "release_readiness",
    "harness_context_integrity",
    "contract_weight_fit",
)

FAILURE_MODES = (
    "missed_existing_path",
    "missed_reuse_surface",
    "over_abstraction",
    "hidden_data_flow",
    "weak_business_orchestration",
    "unsupported_blocker",
    "missing_evidence_verified",
    "artifact_claim_without_evidence",
    "generic_best_practice_over_project_style",
    "missing_project_constraint_in_constitution",
    "downstream_agent_ignored_constitution",
    "constitution_expands_scope",
    "task_context_leaked_into_constitution",
    "platform_agent_rules_leaked_into_constitution",
    "constitution_stage_projection_mismatch",
    "platform_adaptability_gap",
    "response_envelope_ownership_mismatch",
    "identifier_authority_location_mismatch",
    "hidden_business_flow_by_helpers",
    "broken_data_flow_or_copy_semantics",
    "domain_invariant_bypassed",
    "static_evidence_overclaimed_as_runtime_verified",
    "release_readiness_overclaimed",
    "runtime_verification_gap_not_actionable",
    "host_agent_projection_missing",
    "project_profile_commands_not_adopted",
    "frontend_eval_skips_ui_surface",
    "stale_artifact_drift_warning",
    "unmatched_constitution_not_actionable",
    "unrelated_dirty_worktree_included",
    "language_specific_rule_leaked_globally",
    "agent_role_boundary_mismatch",
    "kernel_handoff_blocks_good_code",
    "over_contractual_platform_design",
    "contract_heavy_workflow_blocks_adaptation",
    "prompt_tuning_needed_for_good_code",
    "lane_confusion",
)

SUGGESTED_SIGNALS_BY_DIMENSION = {
    "adopt_artifact_quality": (
        "project rulebook / quality baseline",
        "stable project constraints",
        "project-specific code quality guidance",
        "architecture boundaries and module responsibilities",
        "existing path, reuse surface, data flow, performance, and evidence discipline",
        "exclude task-specific context",
        "avoid generic best practices",
    ),
    "constitution_fit": (
        "constitution is the project rulebook / quality baseline",
        "extract stable project rules that affect future code choices",
        "separate project rules from agent manuals",
        "separate stable project guidance from temporary task context",
        "capture only project constraints reusable across future unrelated tasks",
        "route task details to spec.md, plan.md, tasks.md, or evidence",
    ),
    "scope_boundary": (
        "separate stable project guidance from temporary task context",
        "route current branch, feature, ticket, endpoint, migration phase, task ID, and acceptance criteria out of constitution",
    ),
    "stage_ownership": (
        "constitution owns reusable project quality constraints",
        "spec.md, plan.md, tasks.md, and task evidence own task-specific details",
    ),
    "constitution_downstream_adherence": ("constitution guidance", "downstream agent behavior"),
    "multi_stack_fit": (
        "stack-specific project profile",
        "language/framework-specific verification command",
        "do not treat dependency presence as exercised surface",
    ),
    "project_style_fit": ("current project style", "nearby code conventions"),
    "response_contract_fit": ("response contract", "current endpoint family"),
    "identifier_authority_location": ("identifier authority", "declaration location"),
    "business_orchestration": ("business orchestration", "visible business flow"),
    "data_flow_integrity": ("data flow", "field provenance"),
    "state_transition_integrity": ("state transition", "allowed state flow"),
    "domain_invariant_fit": ("domain invariant", "business rule"),
    "side_effect_visibility": ("side effects", "visible state changes"),
    "persistence_access_shape": ("data access shape", "batch query"),
    "performance_flow": ("performance-sensitive path", "avoid repeated traversal"),
    "artifact_quality": ("artifact state", "actionable artifact drift"),
    "verification_evidence": ("verification evidence", "not verified without evidence", "reproducible verification command"),
    "verification_fit": ("reproducible verification command", "runtime or UI smoke when behavior surface is touched"),
    "release_claim_discipline": ("release claim", "evidence-bounded readiness"),
    "release_readiness": ("release readiness", "blocking verification gaps", "actionable next step before shippable status"),
    "harness_context_integrity": ("scoped context", "runtime evidence", "host-native agent projection", "project profile commands"),
    "contract_weight_fit": (
        "avoid big contractual platform design",
        "keep prompt tuning lightweight and feedback-driven",
        "prove final code quality, not field completeness",
    ),
}
